(setq-default indent-tabs-mode t)
(beacon-mode 0)
(setq-default c-default-style "bsd"
              c-basic-offset 4)
(setq-default tab-width 4)
(setq-default whitespace-line-column 120)
(setq-default whitespace-style '(empty trailing face lines-tail space-mark tab-mark newline newline-mark))
(setq-default whitespace-global-modes '(not org-mode))
(global-prettify-symbols-mode 0)
(global-pretty-mode 0)
